import pandas as pd

def visualize_sampled_data(df: pd.DataFrame) -> pd.DataFrame:
    print(df.info())
    print("--------------------------------")
    print(df["PA_OBITO"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_CONDIC"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_REGCT"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_INCURG"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_TPUPS"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_TIPPRE"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_TPFIN"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_SUBFIN"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_NIVCPL"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_DOCORIG"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_CBOCOD"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_MOTSAI"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_CIDSEC"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_CIDCAS"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_FLIDADE"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_MUNPCN"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_QTDPRO"].describe())
    print("--------------------------------")
    print(df["PA_INDICA"].value_counts(dropna=False))
    print("--------------------------------")
    print(df["PA_VALPRO"].describe())
    print("--------------------------------")
    print(df["PA_VALAPR"].describe())
    print("--------------------------------")
    print(df["PA_QTDPRO"].describe())
    print("--------------------------------")
    df["PA_IDADE"] = df["PA_IDADE"].astype(float)
    print(df["PA_IDADE"].describe())
    print(df[df["PA_IDADE"] > 110].count())
    return True

